import {
  Armchair,
  Baby,
  Bath,
  BedDouble,
  BedSingle,
  BookOpen,
  Box,
  Briefcase,
  Building2,
  Car,
  ChefHat,
  Coffee,
  DoorOpen,
  Dumbbell,
  Fence,
  Flame,
  Flower2,
  Gamepad2,
  Hotel,
  House,
  LampFloor,
  Layers,
  Mountain,
  Music,
  PartyPopper,
  ShowerHead,
  Sofa,
  Sparkles,
  Sun,
  Trees,
  Tv,
  UtensilsCrossed,
  WashingMachine,
  Waves,
  Wine,
  type LucideIcon,
} from "lucide-react";
import type { RoomIconKey } from "@/lib/rooms";

export const ROOM_ICONS: Record<RoomIconKey, LucideIcon> = {
  house: House,
  door: DoorOpen,
  sofa: Sofa,
  chef: ChefHat,
  dining: UtensilsCrossed,
  "bed-double": BedDouble,
  bed: BedSingle,
  bath: Bath,
  shower: ShowerHead,
  briefcase: Briefcase,
  washer: WashingMachine,
  layers: Layers,
  car: Car,
  sun: Sun,
  fence: Fence,
  trees: Trees,
  waves: Waves,
  sparkles: Sparkles,
  armchair: Armchair,
  dumbbell: Dumbbell,
  wine: Wine,
  tv: Tv,
  baby: Baby,
  book: BookOpen,
  coffee: Coffee,
  music: Music,
  party: PartyPopper,
  building: Building2,
  hotel: Hotel,
  mountain: Mountain,
  gamepad: Gamepad2,
  flower: Flower2,
  flame: Flame,
  lamp: LampFloor,
  box: Box,
};

export function RoomIcon({ icon, className, strokeWidth = 1.75 }: { icon: string; className?: string; strokeWidth?: number }) {
  const Icon = ROOM_ICONS[icon as RoomIconKey] ?? Sparkles;
  return <Icon className={className} strokeWidth={strokeWidth} aria-hidden="true" />;
}
